name: Continuous Build and Test

on:
  push:
    branches:
      - main  # Replace "main" with your default branch name, e.g., "master"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add other steps for building and testing your project here
      # For example, if you are using Java and Maven:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn package

      - name: Run tests
        run: mvn test
