name: Java CI with Selenium

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  push:
    branches:
      - main  # Specify the branch you want to trigger the workflow on commit, e.g., main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download chromedriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip -q /tmp/chromedriver_linux64.zip -d /tmp
          chmod +x /tmp/chromedriver
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver

      - name: Build and run Selenium tests
        working-directory: .
        run: mvn clean test -X
