name: Scheduled Build and Test

on:
  schedule:
    - cron: "*/40 * * * *"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn package

      - name: Run tests
        run: mvn test
